### ISSUE TITLE
command line program (mc-cli) dumps when getting data.

### ISSUE THREAD

**Issue by alanrick** [raoulh/mc-cli#5]
The command line program (mc-cli) dumps when using the data argument.
Attached is the output.

However,
C:\....\mc-cli data --help
yields a valid output.
Alan
[mcl-dump.txt](https://github.com/raoulh/mc-cli/files/2174882/mcl-dump.txt)

Moolticute v0.18.7
Windows 10
date of mc-cli.exe 26/June/2018 13:42

**Comment by alanrick** [comment]
I've gone back to 18.1. That works fine,
Alan

**Comment by raoulh** [comment]
Fixed in 2a230bd17230210209e7391cc616975869a0e30b
